---
common_packages:
  - name: curl
  - name: apt-file
  - name: htop
  - name: vim
  - name: git
  - name: iptables

common_backports_packages:
  - name: fish

common_debian_repos:
  - repo: stable
    priority: 900
  - repo: testing
    priority: 750
